from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DeepgramLanguage:
    label: str
    code: str
    target_name: str


@dataclass(frozen=True)
class TranslationLanguage:
    label: str
    name: str


DEEPGRAM_LANGUAGES: tuple[DeepgramLanguage, ...] = (
    DeepgramLanguage("Auto / Multilingual — multi", "multi", "English"),
    DeepgramLanguage("Arabic — ar", "ar", "Arabic"),
    DeepgramLanguage("Arabic UAE — ar-AE", "ar-AE", "Arabic"),
    DeepgramLanguage("Arabic Saudi Arabia — ar-SA", "ar-SA", "Arabic"),
    DeepgramLanguage("Arabic Qatar — ar-QA", "ar-QA", "Arabic"),
    DeepgramLanguage("Arabic Kuwait — ar-KW", "ar-KW", "Arabic"),
    DeepgramLanguage("Arabic Syria — ar-SY", "ar-SY", "Arabic"),
    DeepgramLanguage("Arabic Lebanon — ar-LB", "ar-LB", "Arabic"),
    DeepgramLanguage("Arabic Palestine — ar-PS", "ar-PS", "Arabic"),
    DeepgramLanguage("Arabic Jordan — ar-JO", "ar-JO", "Arabic"),
    DeepgramLanguage("Arabic Egypt — ar-EG", "ar-EG", "Arabic"),
    DeepgramLanguage("Arabic Sudan — ar-SD", "ar-SD", "Arabic"),
    DeepgramLanguage("Arabic Chad — ar-TD", "ar-TD", "Arabic"),
    DeepgramLanguage("Arabic Morocco — ar-MA", "ar-MA", "Arabic"),
    DeepgramLanguage("Arabic Algeria — ar-DZ", "ar-DZ", "Arabic"),
    DeepgramLanguage("Arabic Tunisia — ar-TN", "ar-TN", "Arabic"),
    DeepgramLanguage("Arabic Iraq — ar-IQ", "ar-IQ", "Arabic"),
    DeepgramLanguage("Arabic Iran — ar-IR", "ar-IR", "Arabic"),
    DeepgramLanguage("Belarusian — be", "be", "Belarusian"),
    DeepgramLanguage("Bengali — bn", "bn", "Bengali"),
    DeepgramLanguage("Bosnian — bs", "bs", "Bosnian"),
    DeepgramLanguage("Bulgarian — bg", "bg", "Bulgarian"),
    DeepgramLanguage("Catalan — ca", "ca", "Catalan"),
    DeepgramLanguage("Chinese Cantonese Traditional — zh-HK", "zh-HK", "Chinese"),
    DeepgramLanguage("Chinese Mandarin Simplified — zh", "zh", "Chinese"),
    DeepgramLanguage("Chinese Mandarin Simplified — zh-CN", "zh-CN", "Chinese"),
    DeepgramLanguage("Chinese Mandarin Simplified — zh-Hans", "zh-Hans", "Chinese"),
    DeepgramLanguage("Chinese Mandarin Traditional — zh-TW", "zh-TW", "Chinese"),
    DeepgramLanguage("Chinese Mandarin Traditional — zh-Hant", "zh-Hant", "Chinese"),
    DeepgramLanguage("Croatian — hr", "hr", "Croatian"),
    DeepgramLanguage("Czech — cs", "cs", "Czech"),
    DeepgramLanguage("Danish — da", "da", "Danish"),
    DeepgramLanguage("Danish Denmark — da-DK", "da-DK", "Danish"),
    DeepgramLanguage("Dutch — nl", "nl", "Dutch"),
    DeepgramLanguage("English — en", "en", "English"),
    DeepgramLanguage("English US — en-US", "en-US", "English"),
    DeepgramLanguage("English Australia — en-AU", "en-AU", "English"),
    DeepgramLanguage("English UK — en-GB", "en-GB", "English"),
    DeepgramLanguage("English India — en-IN", "en-IN", "English"),
    DeepgramLanguage("English New Zealand — en-NZ", "en-NZ", "English"),
    DeepgramLanguage("Estonian — et", "et", "Estonian"),
    DeepgramLanguage("Finnish — fi", "fi", "Finnish"),
    DeepgramLanguage("Flemish — nl-BE", "nl-BE", "Dutch"),
    DeepgramLanguage("French — fr", "fr", "French"),
    DeepgramLanguage("French Canada — fr-CA", "fr-CA", "French"),
    DeepgramLanguage("German — de", "de", "German"),
    DeepgramLanguage("German Switzerland — de-CH", "de-CH", "German"),
    DeepgramLanguage("Greek — el", "el", "Greek"),
    DeepgramLanguage("Gujarati — gu", "gu", "Gujarati"),
    DeepgramLanguage("Gujarati India — gu-IN", "gu-IN", "Gujarati"),
    DeepgramLanguage("Hebrew — he", "he", "Hebrew"),
    DeepgramLanguage("Hindi — hi", "hi", "Hindi"),
    DeepgramLanguage("Hungarian — hu", "hu", "Hungarian"),
    DeepgramLanguage("Indonesian — id", "id", "Indonesian"),
    DeepgramLanguage("Italian — it", "it", "Italian"),
    DeepgramLanguage("Japanese — ja", "ja", "Japanese"),
    DeepgramLanguage("Kannada — kn", "kn", "Kannada"),
    DeepgramLanguage("Korean — ko", "ko", "Korean"),
    DeepgramLanguage("Korean Korea — ko-KR", "ko-KR", "Korean"),
    DeepgramLanguage("Latvian — lv", "lv", "Latvian"),
    DeepgramLanguage("Lithuanian — lt", "lt", "Lithuanian"),
    DeepgramLanguage("Macedonian — mk", "mk", "Macedonian"),
    DeepgramLanguage("Malay — ms", "ms", "Malay"),
    DeepgramLanguage("Marathi — mr", "mr", "Marathi"),
    DeepgramLanguage("Norwegian — no", "no", "Norwegian"),
    DeepgramLanguage("Persian — fa", "fa", "Persian"),
    DeepgramLanguage("Polish — pl", "pl", "Polish"),
    DeepgramLanguage("Portuguese — pt", "pt", "Portuguese"),
    DeepgramLanguage("Portuguese Brazil — pt-BR", "pt-BR", "Portuguese"),
    DeepgramLanguage("Portuguese Portugal — pt-PT", "pt-PT", "Portuguese"),
    DeepgramLanguage("Romanian — ro", "ro", "Romanian"),
    DeepgramLanguage("Russian — ru", "ru", "Russian"),
    DeepgramLanguage("Serbian — sr", "sr", "Serbian"),
    DeepgramLanguage("Slovak — sk", "sk", "Slovak"),
    DeepgramLanguage("Slovenian — sl", "sl", "Slovenian"),
    DeepgramLanguage("Spanish — es", "es", "Spanish"),
    DeepgramLanguage("Spanish Latin America — es-419", "es-419", "Spanish"),
    DeepgramLanguage("Swedish — sv", "sv", "Swedish"),
    DeepgramLanguage("Swedish Sweden — sv-SE", "sv-SE", "Swedish"),
    DeepgramLanguage("Tagalog — tl", "tl", "Tagalog"),
    DeepgramLanguage("Tamil — ta", "ta", "Tamil"),
    DeepgramLanguage("Telugu — te", "te", "Telugu"),
    DeepgramLanguage("Thai — th", "th", "Thai"),
    DeepgramLanguage("Thai Thailand — th-TH", "th-TH", "Thai"),
    DeepgramLanguage("Turkish — tr", "tr", "Turkish"),
    DeepgramLanguage("Ukrainian — uk", "uk", "Ukrainian"),
    DeepgramLanguage("Urdu — ur", "ur", "Urdu"),
    DeepgramLanguage("Vietnamese — vi", "vi", "Vietnamese"),
)

TRANSLATION_LANGUAGES: tuple[TranslationLanguage, ...] = (
    TranslationLanguage("Русский — Russian", "Русский"),
    TranslationLanguage("English — Английский", "English"),
    TranslationLanguage("Українська — Ukrainian", "Украинский"),
    TranslationLanguage("Polski — Polish", "Polish"),
    TranslationLanguage("Deutsch — German", "German"),
    TranslationLanguage("Français — French", "French"),
    TranslationLanguage("Español — Spanish", "Spanish"),
    TranslationLanguage("Português — Portuguese", "Portuguese"),
    TranslationLanguage("Italiano — Italian", "Italian"),
    TranslationLanguage("Türkçe — Turkish", "Turkish"),
    TranslationLanguage("العربية — Arabic", "Arabic"),
    TranslationLanguage("中文 — Chinese", "Chinese"),
    TranslationLanguage("日本語 — Japanese", "Japanese"),
    TranslationLanguage("한국어 — Korean", "Korean"),
    TranslationLanguage("हिन्दी — Hindi", "Hindi"),
    TranslationLanguage("Nederlands — Dutch", "Dutch"),
    TranslationLanguage("Svenska — Swedish", "Swedish"),
    TranslationLanguage("Suomi — Finnish", "Finnish"),
    TranslationLanguage("Lietuvių — Lithuanian", "Lithuanian"),
    TranslationLanguage("Latviešu — Latvian", "Latvian"),
    TranslationLanguage("Čeština — Czech", "Czech"),
    TranslationLanguage("Slovenčina — Slovak", "Slovak"),
    TranslationLanguage("Română — Romanian", "Romanian"),
    TranslationLanguage("Български — Bulgarian", "Bulgarian"),
    TranslationLanguage("Српски — Serbian", "Serbian"),
    TranslationLanguage("Hrvatski — Croatian", "Croatian"),
    TranslationLanguage("עברית — Hebrew", "Hebrew"),
    TranslationLanguage("ไทย — Thai", "Thai"),
    TranslationLanguage("Tiếng Việt — Vietnamese", "Vietnamese"),
    TranslationLanguage("Bahasa Indonesia — Indonesian", "Indonesian"),
)


LEGACY_LANGUAGE_LABELS: dict[str, str] = {
    "Auto": "Auto / Multilingual — multi",
    "English": "English — en",
    "Russian": "Russian — ru",
    "Polish": "Polish — pl",
    "German": "German — de",
    "French": "French — fr",
    "Spanish": "Spanish — es",
}
